### ISSUE TITLE
Expanding to More Dense Prediction Tasks

### ISSUE THREAD

**Issue by zhuduowang** [linsun449/iseg.code#2]
Excellent work! Are there any plans to extend this approach to more dense prediction tasks, such as semantic segmentation?

**Comment by linsun449** [comment]
Thanks to the recognition and suggestions for our work. We have already generated and reported pseudo-labels for weakly supervised semantic segmentation in our paper, however we are just starting to train segmentation networks with them. We will publish the code of this part soon, thanks for your attention again!
